package Form;

import Form.Partner.Partner_Registry;
import Form.Partner.Partner_Dashboard;
import Administration.Validation;
import javax.swing.JOptionPane;
/**
 *
 * @author jcebalus
 */
public class Index extends javax.swing.JFrame {

    
    Validation validation = new Validation();
    admin_password admin_password = new admin_password();
    
    
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user_field.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        index_panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        user_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        sign_in_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        sign_up_button = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        administration_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA");

        title.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        title.setText("BIBLIOTECA");

        user_label.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        user_label.setText("Usuario");

        password_label.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        password_label.setText("Contraseña");

        sign_in_button.setText("Ingresar");
        sign_in_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sign_in_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_in_buttonActionPerformed(evt);
            }
        });

        sign_up_button.setText("Registrar");
        sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_up_buttonActionPerformed(evt);
            }
        });

        administration_button.setText("Administración");
        administration_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administration_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout index_panelLayout = new javax.swing.GroupLayout(index_panel);
        index_panel.setLayout(index_panelLayout);
        index_panelLayout.setHorizontalGroup(
            index_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, index_panelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(index_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_label)
                    .addComponent(user_label)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_field)
                    .addComponent(password_field)
                    .addComponent(sign_in_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(sign_up_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(administration_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        index_panelLayout.setVerticalGroup(
            index_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(index_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(78, 78, 78)
                .addComponent(user_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(sign_in_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sign_up_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administration_button)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(index_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(index_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void administration_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administration_buttonActionPerformed
        // TODO add your handling code here:
        admin_password.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        admin_password.setVisible(true);

        this.setVisible(false);
               
    }//GEN-LAST:event_administration_buttonActionPerformed

    private void sign_in_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_in_buttonActionPerformed
        // TODO add your handling code here:
        String user = this.user_field.getText();
        String password = String.valueOf(this.password_field.getPassword());
                
        if(validation.validateUser(user, password)){
            Partner_Dashboard dashboard = new Partner_Dashboard(user);
            this.user_field.setText("");
            this.password_field.setText("");
            
            this.setVisible(false);
            dashboard.setVisible(true);
            dashboard.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        } else {
            this.user_field.setText("");
            this.password_field.setText("");
            JOptionPane.showMessageDialog(this, "Usuario o Contraseña incorrecta");
        }
        
    }//GEN-LAST:event_sign_in_buttonActionPerformed

    private void sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_up_buttonActionPerformed
        // TODO add your handling code here:
        Partner_Registry partner_registry = new Partner_Registry();
        this.setVisible(false);
        partner_registry.setVisible(true);
        
    }//GEN-LAST:event_sign_up_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administration_button;
    private javax.swing.JPanel index_panel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton sign_in_button;
    private javax.swing.JButton sign_up_button;
    private javax.swing.JLabel title;
    private javax.swing.JTextField user_field;
    private javax.swing.JLabel user_label;
    // End of variables declaration//GEN-END:variables
}
